### PR TITLE
Fix bug with RegistryEditor not working in Release build

### PR DESCRIPTION
**Pull request by StingRaptor**
This pull requests contains a fix to the `RegistryEditor` not working in Release (issue:#425, #426), and also a fix to a delete bug for registry keys. Besides this some refactoring of the code has been made to make it more readable.

**Changes made:**
- Added Registry namespace as an exception in Renamer.cs (Prevent obfuscation).
- Removed BackgroundWorker from RegistryEditor
- Added threading to RegistryHandler
- Changed RegSeekerMatch.cs to use Arrays for RegValueData instead of a List
- Activate exceptions for registry key delete operation to correctly signals when a key cannot be deleted

Edit:
- Fixed issue with `RegistryEditor` not working probably on 64-bit systems
- Corrected the title of the form to display as "RegistryEditor - user@pc [IP:PORT]"
- Corrected the size of the form to 800x600

### CODE REVIEW

**Comment by StingRaptor** [comment]
Fixed bug with RegistryEditor not working properly in 64-bit systems.

**Comment by MaxXor** [comment]
Okay, looking good so far. But can u revert the change with the `new Thread(..)` when a registry command is received?

**Comment by StingRaptor** [comment]
Sure, just out of interest what is it that makes threading in this part of the code so bad? Have you found some part where it is not thread safe? Or is it to expensive (resource allocation wise) to create a new thread to handle the registry commands? :smile:

**Comment by MaxXor** [comment]
@StingRaptor It's just not needed imho. The tasks don't take that long to execute.

**Comment by StingRaptor** [comment]
There. I have now removed the Threading from `RegistryHandler` on the client-side. However, I still feel that threading should still have been used on at least `HandleGetRegistryKey` because of the fact that large registrys require almost more than 1 second to finish.

**Comment by MaxXor** [comment]
@StingRaptor Thanks, I'll merge the pull request tomorrow. :+1:

**Pull request merged**
