### PR TITLE
Keylogger Enhancement

### PR DESCRIPTION
**Pull request by Crash129**
Added option to change name of the log directory and to hide it.

### CODE REVIEW

**Comment by yankejustin** [comment]
Thank you for your contribution.
<a href="https://github.com/quasar/QuasarRAT/issues/396">ref</a>

**Comment by Crash129** [comment]
I don't think I got your question right. I think you have to set both attributes, at least based on the sample which I've looked up.

**Comment by Crash129** [comment]
Just saw at MSDN that you can check whether a directory exists via the DirectoryInfo class (https://msdn.microsoft.com/de-de/library/system.io.directoryinfo(v=vs.110).aspx)
This would simplify it even more, I would edit it but I'm new to GitHub and I don't know how to edit my pull request,

**Comment by yankejustin** [comment]
@Crash129 Just add another commit and it will apply to this pull request. :)

**Comment by Crash129** [comment]
@yankejustin Alright, got it :)

**Comment by MaxXor** [comment]
Thanks, good job!

**Pull request merged**
