### PR TITLE
Search functionality for file manager

### PR DESCRIPTION
**Pull request by UbbeLoL**
Added search functionality to the file manager of Quasar.

### CODE REVIEW

**Comment by MaxXor** [comment]
Very nice addition to the File Manager. A few things you should fix before I merge the pull request:
- Remove `Server/Resources/search.bmp` and `Server/images/cross.png ` - they are not used
- Remove the various `Thumbs.db` files Windows created for you
- There exists already a high performance Listview control in `Server/Controls/ListViewEx.cs`, check if it fits your needs and/or merge your changes to this one
- Rename `frmSearchWarning` to `FrmSearchWarning`
- Remove the `app.config` file
- Add back [this line](https://github.com/quasar/QuasarRAT/pull/574/files#diff-68a39551b0b0d04313d8910a2ac8d875L15)

And thanks for your work. 👍

**Comment by UbbeLoL** [comment]
I think the latest commit should cover all the things you mentioned. :)

**Comment by kernelzr** [comment]
Some folders while browsing are displaying this error "GetDirectory Faild" for example "C:\User\MyRemoteUser\AppData\" . Does this problem happen to you? I'm using the BUILD282. Previous versions did not happen.

**Comment by UbbeLoL** [comment]
@kernelzr do you have any more info you can provide regarding the specific folders that generate the error? It's hard to replicate not knowing the conditions.

**Comment by kernelzr** [comment]
I have not found anything specific that justifies this error, the Remote Shell can access any folder. I tested on many machines and in all the folder "AppData" inside the user folder does not browse. It would be interesting to implement the complete error exit next to "GetDirectory Fail", for example:

Status: "GetDirectory Fail" - Here the execption of program

In java I would do this:

```
....
} Catch (Exception e) {
 Label.setText ("Status: GetDirectory Fail" + e.getErro());
}
```

**Comment by UbbeLoL** [comment]
@kernelzr Thanks for the report, I'll look into it when I get some time over. :+1:

**Pull request closed without merging**
