### PR TITLE
Removed unused Firefox stuff

### PR DESCRIPTION
**Pull request by Rottweiler**
Removed unused/not needed Firefox recovery libs+functions+calls

Firefox recovery currently fails at LoadLibrary->nss3.dll, (or alternately NSS_Init call). I got it working on Windows 10 x64 when providing hardcoded path to install directory + compiling under x86

### CODE REVIEW

**Comment by d3agle** [comment]
Can you hold off on this I'm deep into it :D  Got a whole bunch of fixes for this

**Comment by Rottweiler** [comment]
This is very messy code, but this example currently works (Visual Basic .NET) https://raw.githubusercontent.com/rotthh/PREC/master/prec.vb

**Comment by Rottweiler** [comment]
All right, should I close the pull request?

**Comment by d3agle** [comment]
Yes, please :)  I've tested earlier versions and those calls are needed to load the DLLs properly

**Comment by Rottweiler** [comment]
Sure.

**Comment by d3agle** [comment]
Thanks!  When I make the PR, would you be able to test it?

**Comment by Rottweiler** [comment]
Absolutely

**Comment by d3agle** [comment]
Awesome, thank you! #343

**Pull request closed without merging**
